# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacherProfile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['Class', 'studying_subjects', '-created_at'], name='teacherProf_Class_78abac_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['Class', 'studying_subjects', '-number_of_exams'], name='teacherProf_Class_13d6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['Class', 'studying_subjects', '-number_of_notes'], name='teacherProf_Class_75421b_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['Class', 'studying_subjects', '-number_of_courses'], name='teacherProf_Class_e4fa23_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['Class', 'studying_subjects', '-number_of_followers'], name='teacherProf_Class_5f83d4_idx'),
        ),
    ]
