# Generated by Django 5.2.5 on 2025-11-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherProfile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='university',
            field=models.CharField(blank=True, default='', help_text='اسم الجامعة التي تدرس فيها أو تخرجت منها', max_length=100, verbose_name='الجامعة'),
        ),
    ]
