# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('question_image', models.CharField(blank=True, max_length=400, null=True)),
                ('option_A', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('option_B', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('option_C', models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('option_D', models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('option_E', models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('right_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('explanation', models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('is_arabic', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
