# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0003_alter_mcq_options'),
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcq',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['-created_at'], name='MCQ_mcq_created_0ddd13_idx'),
        ),
    ]
