# Generated by Django 5.2.8 on 2025-12-09 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0004_alter_mcq_options_mcq_mcq_mcq_created_0ddd13_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='explanation',
            field=models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_A',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_B',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_C',
            field=models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_D',
            field=models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_E',
            field=models.TextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
