# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videos_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['-created_at'], name='videos_vide_created_2c0850_idx'),
        ),
    ]
