# Generated by Django 5.2.8 on 2025-12-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='file_unique_name',
        ),
    ]
