# Generated by Django 5.2.8 on 2025-12-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_videos_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videos',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
