# Generated by Django 5.2.8 on 2025-12-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_videos_video_url_videos_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='video_explanation',
            new_name='explanation',
        ),
    ]
