# Generated by Django 5.2.8 on 2025-12-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_rename_video_explanation_videos_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
