# Generated by Django 5.2.8 on 2025-12-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_videos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='explanation',
            field=models.TextField(blank=True, default='', max_length=40000, null=True),
        ),
    ]
