# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisherOffers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('auto_renew', models.BooleanField(blank=True, default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_publisher_plans', to='publisherOffers.publisheroffers')),
            ],
            options={
                'ordering': ['-activation_date'],
            },
        ),
    ]
