# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('account_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('team', 'Team'), ('admin', 'Admin')], default='student', max_length=20)),
                ('first_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2, 'يجب ألا يكون الاسم الأول أقصر من حرفين'), django.core.validators.RegexValidator(code='invalid_arabic', message='يجب أن يحتوي الاسم على أحرف عربية فقط', regex='^[\\u0600-\\u06FF\\s\\u0750-\\u077F\\u08A0-\\u08FF]+$')])),
                ('last_name', models.CharField(blank=True, default='', max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_arabic', message='يجب أن يحتوي الاسم على أحرف عربية فقط', regex='^[\\u0600-\\u06FF\\s\\u0750-\\u077F\\u08A0-\\u08FF]+$')])),
                ('full_name', models.CharField(blank=True, default='', help_text='اسم المعلم الكامل', max_length=250, verbose_name='الاسم الكامل')),
                ('team_name', models.CharField(blank=True, default='', help_text='اسم الفريق', max_length=250, verbose_name='اسم الفريق')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(7, 'يجب ألا يكون الاسم الأخير أقصر من 7 حروف'), django.core.validators.RegexValidator(code='invalid_phone', message='يجب أن يحتوي رقم الهاتف على 8 إلى 12 رقم فقط', regex='^[0-9]{8,12}$')])),
                ('image', models.CharField(blank=True, max_length=300)),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', max_length=2)),
                ('city', models.CharField(choices=[('حمص', 'العادية حمص'), ('إدلب', 'إدلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('دير الزور', 'دير الزور'), ('ريف دمشق', 'ريف دمشق'), ('درعا', 'درعا'), ('طرطوس', 'طرطوس'), ('اللاذقية', 'اللاذقية'), ('الحسكة', 'الحسكة'), ('القنيطرة', 'القنيطرة'), ('حماة', 'حماة'), ('الرقة', 'الرقة')], default='حمص', max_length=60)),
                ('is_account_confirmed', models.BooleanField(blank=True, default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='لا يمكن للرصيد أن يكون سالب')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_banned', models.BooleanField(blank=True, default=False)),
                ('banned_date', models.DateField(blank=True, null=True)),
                ('banning_reason', models.CharField(blank=True, max_length=2000)),
                ('banned_until', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=2000)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
