# Generated by Django 5.2.8 on 2025-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_users_user_telegra_1e47e4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('حمص', 'العادية حمص'), ('إدلب', 'إدلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('دير الزور', 'دير الزور'), ('ريف دمشق', 'ريف دمشق'), ('درعا', 'درعا'), ('طرطوس', 'طرطوس'), ('اللاذقية', 'اللاذقية'), ('الحسكة', 'الحسكة'), ('قنيطرة', 'قنيطرة'), ('حماة', 'حماة'), ('الرقة', 'الرقة')], default='حمص', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True),
        ),
    ]
