# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
import teamProfile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_exams', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='عدد الامتحانات لا يمكن أن يكون سالب')], verbose_name='عدد الامتحانات')),
                ('number_of_notes', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='عدد الملاحظات لا يمكن أن يكون سالب')], verbose_name='عدد الملاحظات')),
                ('number_of_courses', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='عدد الكورسات لا يمكن أن يكون سالب')], verbose_name='عدد الكورسات')),
                ('number_of_followers', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='عدد المتابعين لا يمكن أن يكون سالب')], verbose_name='عدد المتابعين')),
                ('telegram_link', models.URLField(blank=True, null=True, validators=[teamProfile.models.validate_social_media_url], verbose_name='رابط التليجرام')),
                ('whatsapp_link', models.URLField(blank=True, null=True, validators=[teamProfile.models.validate_social_media_url], verbose_name='رابط الواتساب')),
                ('instagram_link', models.URLField(blank=True, null=True, validators=[teamProfile.models.validate_social_media_url], verbose_name='رابط الانستغرام')),
                ('facebook_link', models.URLField(blank=True, null=True, validators=[teamProfile.models.validate_social_media_url], verbose_name='رابط الفيسبوك')),
                ('x_link', models.URLField(blank=True, null=True, validators=[teamProfile.models.validate_social_media_url], verbose_name='رابط إكس (تويتر)')),
                ('linkedin_link', models.URLField(blank=True, null=True, validators=[teamProfile.models.validate_social_media_url], verbose_name='رابط لينكد إن')),
                ('verified', models.BooleanField(default=False, verbose_name='حساب موثق')),
                ('address', models.TextField(blank=True, help_text='العنوان الكامل', max_length=500, verbose_name='العنوان')),
                ('bio', models.TextField(blank=True, help_text='اكتب نبذة عن الفريق وخبراته', max_length=1000, verbose_name='نبذة شخصية')),
                ('years_of_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='سنوات الخبرة لا يمكن أن تكون سالبة'), django.core.validators.MaxValueValidator(50, message='سنوات الخبرة لا يمكن أن تكون أكثر من 50 سنة')], verbose_name='سنوات الخبرة')),
            ],
            options={
                'verbose_name': 'ملف الفريق',
                'verbose_name_plural': 'ملفات الفرق',
            },
        ),
    ]
