# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamProfile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='teamprofile',
            index=models.Index(fields=['-created_at'], name='teamProfile_created_758396_idx'),
        ),
        migrations.AddIndex(
            model_name='teamprofile',
            index=models.Index(fields=['-number_of_exams'], name='teamProfile_number__ee6122_idx'),
        ),
        migrations.AddIndex(
            model_name='teamprofile',
            index=models.Index(fields=['-number_of_notes'], name='teamProfile_number__e25881_idx'),
        ),
        migrations.AddIndex(
            model_name='teamprofile',
            index=models.Index(fields=['-number_of_courses'], name='teamProfile_number__b982c4_idx'),
        ),
        migrations.AddIndex(
            model_name='teamprofile',
            index=models.Index(fields=['-number_of_followers'], name='teamProfile_number__3ac7ff_idx'),
        ),
    ]
