"""
Django settings for siraj project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-#ugoyn1(ts%o5lkg0jag33itk3bvxxa(ou*mtr8#9o8+&80q#b'
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [  
     "localhost",
    "127.0.0.1",
    "siraj-frontend.vercel.app",
    ]   

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Your Vite development server origin
    "http://127.0.0.1:5173",  # Optional: if you also use the IP address
    
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://siraj-frontend.vercel.app",
    
    "http://localhost:3000",  # Default React port
    "http://127.0.0.1:3000",
    
]
# This is crucial for allowing credentials like cookies
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF trusted origins for Django
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://siraj-frontend.vercel.app",
]

# For development - you can disable CSRF for API endpoints or configure properly
CSRF_COOKIE_SAMESITE = None
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False # Set to True in production (HTTPS only)
CSRF_COOKIE_SECURE = False # Set to True in production (HTTPS only)

# If you're using CSRF protection, you might need this
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
# DO NOT use CORS_ALLOW_ALL_ORIGINS = True when CORS_ALLOW_CREDENTIALS = True
# Browsers will reject credentials with wildcard origins
# CORS_ALLOW_ALL_ORIGINS = True

CELERY_BROKER_URL = "redis://default:IPcbXMHQIps4ABSbzq7qny4Sd8Wco6BT@redis-15737.c92.us-east-1-3.ec2.redns.redis-cloud.com:15737/0"
CELERY_RESULT_BACKEND = "redis://default:IPcbXMHQIps4ABSbzq7qny4Sd8Wco6BT@redis-15737.c92.us-east-1-3.ec2.redns.redis-cloud.com:15737/0"
CELERY_ACCEPT_CONTENT = ["json"]  # Only accept JSON content
CELERY_TASK_SERIALIZER = "json"  # Serialize tasks as JSON
CELERY_RESULT_SERIALIZER = "json"  # Serialize results as JSON
CELERY_TIMEZONE = "UTC"  # Use UTC timezone


# Application definition
INSTALLED_APPS = [
  "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "storages",
    "boto3",
    "adminApp",
    "teacherProfile",
    "teamProfile",
    "publisherOffers",
    "publisherPlans",
    "publisherVerificationRequests",
    "studentProfile",
    "studentPremiumContent",
    "studentSavedElements",
    "studentSubjectTracking",
    "exams",
    "MCQ",
    "examAppTracking",
    "notes",
    "notesAppendixes",
    "noteReadTracking",
    "courses",
    "lessons",
    "courseStatusTracking",
    "videos",
    "purchaseHistory",
    "transactions",
    "chargingOrders",
    "withdrawBalanceRequest",
    "users",
    "userOTP",
    "images",
    "discountCodes",
    "reports",
    "posts",
    "notifications",
    "comments",
    "followers",
    "servicePurchaseHistory",
    "units",
    
    # "telegramBot",
]

MIDDLEWARE = [
        "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'siraj.urls'

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")

SITE_NAME = "سراج التعليمية"
SITE_URL = "https://siraj.sy"
SUPPORT_EMAIL = "support@siraj.sy"


TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # ← Add this line
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siraj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DEVELOPMENT_DB_NAME' , "default_value"),
        'USER': os.getenv('DEVELOPMENT_DB_USER',"default_value"),
        'PASSWORD':os.getenv('DEVELOPMENT_DB_PASSWORD',"default_value"),
        'HOST':os.getenv('DEVELOPMENT_DB_HOST',"default_value"),
        'PORT':int(os.getenv('DEVELOPMENT_DB_PORT',"3306")),
 
    }
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = f" منصة سراج التعليمية<{EMAIL_HOST_USER}>"
EMAIL_FROM = f"منصة سراج التعليمية <{EMAIL_HOST_USER}>"

AWS_BUCKET_NAME = os.getenv("AWS_BUCKET_NAME")
AWS_REGION_NAME = os.getenv("AWS_REGION_NAME")
AWS_ENDPOINT_URL = os.getenv("AWS_ENDPOINT_URL")


AWS_PRIVATE_BUCKET_NAME =os.getenv("AWS_PRIVATE_BUCKET_NAME")
AWS_PRIVATE_REGION_NAME =os.getenv("AWS_PRIVATE_REGION_NAME")
AWS_PRIVATE_ENDPOINT_URL = os.getenv("AWS_PRIVATE_ENDPOINT_URL")

AWS_PUBLIC_BUCKET_NAME = os.getenv("AWS_PUBLIC_BUCKET_NAME")
AWS_PUBLIC_REGION_NAME = os.getenv("AWS_PUBLIC_REGION_NAME")
AWS_PUBLIC_ENDPOINT_URL =os.getenv("AWS_PUBLIC_ENDPOINT_URL")

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
 


STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,  # application key id
            "secret_key": AWS_SECRET_ACCESS_KEY,  # application key
            "bucket_name": AWS_PRIVATE_BUCKET_NAME,
            "region_name": AWS_PRIVATE_REGION_NAME,
            "endpoint_url": AWS_PRIVATE_ENDPOINT_URL,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Where collected static files will be stored
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Additional locations for static files
# Only include if the directory exists
static_dir = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    static_dir,
] if os.path.exists(static_dir) else []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/min",  # 100 requests per minute for anonymous users
        "user": "200/min",  # 200 requests per minute for authenticated users
        "public_teacher_profile": "10/min",
        "public_team_profile": "10/min",
        "public_student_profile": "10/min",
        "create_charging_order": "2/day",
        "make_withdraw_balance_request": "2/day",
        "resend_otp": "1/min",
        "verify_account": "2/min",
    },
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ),
}

 



SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=100),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=90),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


AUTH_USER_MODEL = "users.User"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
