# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAppTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_apps', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('result_of_first_app', models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_app_date', models.DateTimeField(auto_now=True)),
                ('result_of_last_app', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('highest_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lowest_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('result_average', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('time_of_first_app', models.IntegerField(blank=True, default=0)),
                ('shortest_time', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
