# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examAppTracking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examapptracking',
            name='publisher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_app_tracking_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examapptracking',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_app_tracking_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='examapptracking',
            index=models.Index(fields=['student_id', '-created_at'], name='examAppTrac_student_d79883_idx'),
        ),
        migrations.AddIndex(
            model_name='examapptracking',
            index=models.Index(fields=['publisher_id', '-created_at'], name='examAppTrac_publish_41e8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='examapptracking',
            index=models.Index(fields=['exam_id', '-created_at'], name='examAppTrac_exam_id_b6e906_idx'),
        ),
    ]
