# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_image'),
        ('exams', '0002_initial'),
        ('notes', '0003_alter_note_description'),
        ('studentSavedElements', '0003_alter_studentsavedelements_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsavedelements',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='studentsavedelements',
            index=models.Index(fields=['-created_at'], name='studentSave_created_c22cb9_idx'),
        ),
    ]
