# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_description'),
        ('notesAppendixes', '0002_alter_notesappendixes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notesappendixes',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='notesappendixes',
            index=models.Index(fields=['-created_at'], name='notesAppend_created_476075_idx'),
        ),
    ]
