# Generated by Django 5.2.8 on 2025-12-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Unique name for this unit/tag (e.g., 'Algebra Basics', 'Organic Chemistry')", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this unit covers', max_length=500, null=True)),
                ('Class', models.CharField(choices=[('6', 'السادس'), ('7', 'السابع'), ('8', 'الثامن'), ('9', 'التاسع'), ('10', 'العاشر'), ('11', 'الحادي عشر'), ('12', 'بكلوريا')], max_length=200)),
                ('subject_name', models.CharField(choices=[('math', 'الرياضيات'), ('english', 'اللغة الإنجليزية'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('history', 'التاريخ'), ('geography', 'الجغرافيا'), ('social', 'اجتماعيات'), ('islam', 'الديانة الإسلامية'), ('science', 'العلوم'), ('chemistry', ' كيمياء'), ('physics', 'فيزياء'), ('philosophy', 'فلسفة'), ('physics_chemistry', 'فيزياء و كيمياء')], max_length=200)),
                ('slug', models.SlugField(editable=False, help_text='URL-friendly version of the unit name', max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'indexes': [models.Index(fields=['name'], name='units_unit_name_a384d5_idx'), models.Index(fields=['slug'], name='units_unit_slug_aceb5e_idx')],
            },
        ),
    ]
