# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher_name', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(2)])),
                ('content_type', models.CharField(default='', max_length=50)),
                ('content_id', models.IntegerField(default=0)),
                ('content_name', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(2)])),
                ('content_class', models.CharField(choices=[('6', 'السادس'), ('7', 'السابع'), ('8', 'الثامن'), ('9', 'التاسع'), ('10', 'العاشر'), ('11', 'الحادي عشر'), ('12', 'بكلوريا')], default='12', max_length=6)),
                ('content_subject_name', models.CharField(choices=[('math', 'الرياضيات'), ('english', 'اللغة الإنجليزية'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('history', 'التاريخ'), ('geography', 'الجغرافيا'), ('social', 'اجتماعيات'), ('islam', 'الديانة الإسلامية'), ('science', 'العلوم'), ('chemistry', ' كيمياء'), ('physics', 'فيزياء'), ('philosophy', 'فلسفة'), ('physics_chemistry', 'فيزياء و كيمياء')], default='math', max_length=60)),
                ('student_name', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(2)])),
                ('student_city', models.CharField(choices=[('حمص', 'العادية حمص'), ('إدلب', 'إدلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('دير الزور', 'دير الزور'), ('ريف دمشق', 'ريف دمشق'), ('درعا', 'درعا'), ('طرطوس', 'طرطوس'), ('اللاذقية', 'اللاذقية'), ('الحسكة', 'الحسكة'), ('القنيطرة', 'القنيطرة'), ('حماة', 'حماة'), ('الرقة', 'الرقة')], default='حمص', max_length=50)),
                ('student_gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', max_length=1)),
                ('student_class', models.CharField(choices=[('6', 'السادس'), ('7', 'السابع'), ('8', 'الثامن'), ('9', 'التاسع'), ('10', 'العاشر'), ('11', 'الحادي عشر'), ('12', 'بكلوريا')], default='12', max_length=6)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('publisher_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_code', models.CharField(blank=True, default='-', max_length=50)),
                ('discount_value', models.CharField(blank=True, default='0', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
