# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseHistory', '0003_alter_purchasehistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['-created_at'], name='purchaseHis_created_cec411_idx'),
        ),
    ]
