# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['comment_id', '-created_at'], name='comments_co_comment_5f55a2_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['exam_id', '-created_at'], name='comments_co_exam_id_90e659_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['note_id', '-created_at'], name='comments_co_note_id_508384_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['course_id', '-created_at'], name='comments_co_course__3dc863_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post_id', '-created_at'], name='comments_co_post_id_813c7e_idx'),
        ),
    ]
