# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_way', models.CharField(default='', max_length=50)),
                ('payment_photo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('pending', 'قيد المراجعة'), ('confirmed', 'تم التأكيد'), ('cancelled', 'تم الإلغاء')], default='pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
