# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargingOrders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingorders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_orders_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chargingorders',
            index=models.Index(fields=['status', '-created_at'], name='chargingOrd_status_e28cf3_idx'),
        ),
    ]
