# Generated by Django 5.2.8 on 2025-11-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingOrders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingorders',
            name='payment_photo',
            field=models.ImageField(blank=True, default='', upload_to='charging_orders/payment_photos/'),
        ),
    ]
