# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Class', models.CharField(choices=[('6', 'السادس'), ('7', 'السابع'), ('8', 'الثامن'), ('9', 'التاسع'), ('10', 'العاشر'), ('11', 'الحادي عشر'), ('12', 'بكلوريا')], help_text='الصف الذي تدرس فيه', max_length=6, verbose_name='الصف')),
                ('school', models.CharField(blank=True, help_text='اسم المدرسة التي تدرس فيها', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'يجب ألا يكون الاسم الأول أقصر من حرفين'), django.core.validators.RegexValidator(code='invalid_arabic', message='يجب أن يحتوي الاسم على أحرف عربية فقط', regex='^[\\u0600-\\u06FF\\s\\u0750-\\u077F\\u08A0-\\u08FF]+$')], verbose_name='المدرسة')),
                ('number_of_done_exams', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='عدد الامتحانات المنجزة لا يمكن أن يكون سالب')], verbose_name='عدد الامتحانات المنجزة')),
                ('number_of_read_notes', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='عدد الملاحظات المقروءة لا يمكن أن يكون سالب')], verbose_name='عدد الملاحظات المقروءة')),
                ('number_of_completed_courses', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='عدد الكورسات المكتملة لا يمكن أن يكون سالب')], verbose_name='عدد الكورسات المكتملة')),
            ],
            options={
                'verbose_name': 'ملف الطالب',
                'verbose_name_plural': 'ملفات الطلاب',
                'ordering': ['-id'],
            },
        ),
    ]
