# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'اسم الامتحان يجب ان يكون اطول من 3 حروف')])),
                ('units', models.CharField(default='', max_length=2000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Class', models.CharField(choices=[('6', 'السادس'), ('7', 'السابع'), ('8', 'الثامن'), ('9', 'التاسع'), ('10', 'العاشر'), ('11', 'الحادي عشر'), ('12', 'بكلوريا')], default='12', max_length=6)),
                ('subject_name', models.CharField(choices=[('math', 'الرياضيات'), ('english', 'اللغة الإنجليزية'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('history', 'التاريخ'), ('geography', 'الجغرافيا'), ('social', 'اجتماعيات'), ('islam', 'الديانة الإسلامية'), ('science', 'العلوم'), ('chemistry', ' كيمياء'), ('physics', 'فيزياء'), ('philosophy', 'فلسفة'), ('physics_chemistry', 'فيزياء و كيمياء')], default='math', max_length=60)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_apps', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_purchases', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_questions', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_comments', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('result_avg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.CharField(choices=[('سهل', 'سهل'), ('متوسط', 'متوسط'), ('صعب', 'صعب')], default='سهل', max_length=6)),
                ('description', models.TextField(default='', max_length=1000)),
                ('visibility', models.CharField(blank=True, default='public', max_length=10)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('disable_date', models.DateTimeField(blank=True, null=True)),
                ('disabled_by', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
