# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='publisher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['active', 'visibility', 'subject_name', 'Class', '-created_at'], name='exams_exam_active_7c461a_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['active', 'visibility', 'subject_name', 'Class', '-number_of_apps'], name='exams_exam_active_f5c665_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['active', 'visibility', 'subject_name', 'Class', '-number_of_purchases'], name='exams_exam_active_33dd44_idx'),
        ),
    ]
