# Generated by Django 5.2.8 on 2025-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='units',
        ),
        migrations.AddField(
            model_name='exam',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='exams', to='units.unit'),
        ),
    ]
