# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentPremiumContent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpremiumcontent',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_premium_content_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpremiumcontent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_premium_content_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
