# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['active', 'visibility', 'subject_name', 'Class', '-created_at'], name='notes_note_active_d1205a_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['active', 'visibility', 'subject_name', 'Class', '-number_of_downloads'], name='notes_note_active_dcd270_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['active', 'visibility', 'subject_name', 'Class', '-number_of_purchases'], name='notes_note_active_47fc29_idx'),
        ),
    ]
