# Generated by Django 5.2.5 on 2025-11-20 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1500, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
