# Generated by Django 5.2.8 on 2026-01-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='file_unique_name',
        ),
    ]
