# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_name', models.CharField(default='', max_length=100)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('offer_for', models.CharField(choices=[('teacher', 'teacher'), ('team', 'team')], default='teacher', max_length=20)),
                ('number_of_exams', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_notes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_courses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
