# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisherOffers', '0002_alter_publisheroffers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisheroffers',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='publisheroffers',
            index=models.Index(fields=['-created_at'], name='publisherOf_created_8f10d7_idx'),
        ),
    ]
