# Generated by Django 5.2.5 on 2025-11-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.CharField(help_text='رمز التحقق المكون من 4 أرقام', max_length=4, verbose_name='رمز التحقق')),
                ('expire_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_used', models.BooleanField(blank=True, default=False, verbose_name='تم الاستخدام')),
                ('purpose', models.CharField(default='email_verification', help_text='الغرض من رمز التحقق', max_length=50, verbose_name='الغرض')),
            ],
            options={
                'verbose_name': 'رمز تحقق المستخدم',
                'verbose_name_plural': 'رموز تحقق المستخدمين',
            },
        ),
    ]
