# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(2, 'يجب ألا يكون الاسم أقصر من حرفين')])),
                ('transaction_type', models.CharField(choices=[('withdraw', 'withdraw'), ('purchase', 'purchase'), ('charge', 'charge'), ('bonus', 'bonus'), ('penalty', 'penalty')], default='purchase', max_length=50)),
                ('transaction_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
