# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['-created_at'], name='transaction_created_c03e33_idx'),
        ),
    ]
