# Generated by Django 5.2.8 on 2025-11-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'withdraw'), ('purchase', 'purchase'), ('subscription', 'subscription'), ('charge', 'charge'), ('bonus', 'bonus'), ('penalty', 'penalty')], default='purchase', max_length=50),
        ),
    ]
