# Generated by Django 5.2.5 on 2025-11-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=300)),
                ('reported_user_full_name', models.CharField(default='', max_length=300)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_description', models.TextField(default='', max_length=1000)),
                ('reported_content_type', models.CharField(default='', max_length=50)),
                ('verified', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
