# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reports_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='reports',
            index=models.Index(fields=['-created_at'], name='reports_rep_created_134d1d_idx'),
        ),
    ]
