# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_options'),
        ('posts', '0004_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created_at'], name='images_imag_created_62db75_idx'),
        ),
    ]
