# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['active', 'subject_name', 'Class', '-created_at'], name='courses_cou_active_5bdf63_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['active', 'subject_name', 'Class', '-number_of_enrollments'], name='courses_cou_active_291e05_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['active', 'subject_name', 'Class', '-number_of_purchases'], name='courses_cou_active_5540db_idx'),
        ),
    ]
