# Generated by Django 5.2.5 on 2025-11-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
