# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noteReadTracking', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notereadtracking',
            name='note_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_read_tracking_note', to='notes.note'),
        ),
    ]
