# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noteReadTracking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notereadtracking',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_read_tracking_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notereadtracking',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_read_tracking_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notereadtracking',
            index=models.Index(fields=['student_id', '-created_at'], name='noteReadTra_student_e55664_idx'),
        ),
        migrations.AddIndex(
            model_name='notereadtracking',
            index=models.Index(fields=['publisher_id', '-created_at'], name='noteReadTra_publish_734242_idx'),
        ),
        migrations.AddIndex(
            model_name='notereadtracking',
            index=models.Index(fields=['note_id', '-created_at'], name='noteReadTra_note_id_986bdb_idx'),
        ),
    ]
