# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawBalanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=15)),
                ('city', models.CharField(choices=[('حمص', 'العادية حمص'), ('إدلب', 'إدلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('دير الزور', 'دير الزور'), ('ريف دمشق', 'ريف دمشق'), ('درعا', 'درعا'), ('طرطوس', 'طرطوس'), ('اللاذقية', 'اللاذقية'), ('الحسكة', 'الحسكة'), ('القنيطرة', 'القنيطرة'), ('حماة', 'حماة'), ('الرقة', 'الرقة')], default='', max_length=50)),
                ('original_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wanted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('confirmed', models.BooleanField(blank=True, default=False)),
                ('confirmation_date_time', models.DateTimeField(blank=True, null=True)),
                ('payment_way', models.CharField(default='', max_length=200)),
                ('shamcash_code', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
