# Generated by Django 5.2.8 on 2025-12-27 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawBalanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=15)),
                ('city', models.CharField(choices=[('حمص', 'العادية حمص'), ('إدلب', 'إدلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('دير الزور', 'دير الزور'), ('ريف دمشق', 'ريف دمشق'), ('درعا', 'درعا'), ('طرطوس', 'طرطوس'), ('اللاذقية', 'اللاذقية'), ('الحسكة', 'الحسكة'), ('قنيطرة', 'قنيطرة'), ('حماة', 'حماة'), ('الرقة', 'الرقة')], default='', max_length=50)),
                ('original_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wanted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('confirmed', models.BooleanField(blank=True, default=False)),
                ('confirmation_date_time', models.DateTimeField(blank=True, null=True)),
                ('payment_way', models.CharField(default='', max_length=200)),
                ('meta_data', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['-created_at'], name='withdrawBal_created_d898d7_idx')],
            },
        ),
    ]
