# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherVerificationRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(2, 'يجب ألا يكون الاسم أقصر من حرفين')])),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=255)),
                ('image1', models.CharField(default='', max_length=300)),
                ('image2', models.CharField(default='', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'جاري التحقق'), ('approved', 'تم التحقق'), ('rejected', 'مرفوض')], default='pending', max_length=40)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
