# Generated by Django 5.2.8 on 2025-11-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisherVerificationRequests', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisherverificationrequests',
            options={'ordering': []},
        ),
        migrations.AlterField(
            model_name='publisherverificationrequests',
            name='image1',
            field=models.ImageField(default='', upload_to='publisher_verification_requests/images/'),
        ),
        migrations.AlterField(
            model_name='publisherverificationrequests',
            name='image2',
            field=models.ImageField(default='', upload_to='publisher_verification_requests/images/'),
        ),
    ]
