# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisherVerificationRequests', '0003_alter_publisherverificationrequests_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisherverificationrequests',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='publisherverificationrequests',
            index=models.Index(fields=['-created_at'], name='publisherVe_created_1706c9_idx'),
        ),
    ]
