# Generated by Django 5.2.8 on 2025-11-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisherVerificationRequests', '0004_alter_publisherverificationrequests_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisherverificationrequests',
            name='email',
        ),
        migrations.RemoveField(
            model_name='publisherverificationrequests',
            name='name',
        ),
        migrations.RemoveField(
            model_name='publisherverificationrequests',
            name='phone',
        ),
    ]
