# Generated by Django 5.2.8 on 2025-12-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, verbose_name='اسم الملف')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
            ],
            options={
                'indexes': [models.Index(fields=['expiration_date'], name='tempUploads_expirat_8dd63c_idx')],
            },
        ),
    ]
