# Generated by Django 5.2.8 on 2025-12-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempUploads', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tempupload',
            index=models.Index(fields=['name'], name='tempUploads_name_2959d0_idx'),
        ),
    ]
