# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_alter_followers_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='followers',
            index=models.Index(fields=['-created_at'], name='followers_f_created_d21aeb_idx'),
        ),
    ]
