# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseStatusTracking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestatustracking',
            name='publisher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_status_tracking_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursestatustracking',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_status_tracking_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coursestatustracking',
            index=models.Index(fields=['student_id', '-created_at'], name='courseStatu_student_ba7fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='coursestatustracking',
            index=models.Index(fields=['publisher_id', '-created_at'], name='courseStatu_publish_95adc3_idx'),
        ),
        migrations.AddIndex(
            model_name='coursestatustracking',
            index=models.Index(fields=['course_id', '-created_at'], name='courseStatu_course__480964_idx'),
        ),
    ]
