# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Class', models.CharField(choices=[('6', 'السادس'), ('7', 'السابع'), ('8', 'الثامن'), ('9', 'التاسع'), ('10', 'العاشر'), ('11', 'الحادي عشر'), ('12', 'بكلوريا')], default='12', max_length=6)),
                ('subject_name', models.CharField(choices=[('math', 'الرياضيات'), ('english', 'اللغة الإنجليزية'), ('arabic', 'اللغة العربية'), ('french', 'اللغة الفرنسية'), ('history', 'التاريخ'), ('geography', 'الجغرافيا'), ('social', 'اجتماعيات'), ('islam', 'الديانة الإسلامية'), ('science', 'العلوم'), ('chemistry', ' كيمياء'), ('physics', 'فيزياء'), ('philosophy', 'فلسفة'), ('physics_chemistry', 'فيزياء و كيمياء')], default='math', max_length=25)),
                ('number_of_exams', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_notes', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_courses', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Student Subject Tracking',
                'verbose_name_plural': 'Student Subject Trackings',
            },
        ),
    ]
