# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentSubjectTracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjecttracking',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_tracking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentsubjecttracking',
            index=models.Index(fields=['student_id', 'Class', 'subject_name', '-created_at'], name='studentSubj_student_40d38e_idx'),
        ),
    ]
