# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(2)])),
                ('user_type', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('city', models.CharField(choices=[('حمص', 'العادية حمص'), ('إدلب', 'إدلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('دير الزور', 'دير الزور'), ('ريف دمشق', 'ريف دمشق'), ('درعا', 'درعا'), ('طرطوس', 'طرطوس'), ('اللاذقية', 'اللاذقية'), ('الحسكة', 'الحسكة'), ('القنيطرة', 'القنيطرة'), ('حماة', 'حماة'), ('الرقة', 'الرقة')], default='حمص', max_length=30)),
                ('service_name', models.CharField(default='', max_length=500, validators=[django.core.validators.MinLengthValidator(2)])),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
