# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePurchaseHistory', '0003_alter_servicepurchasehistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepurchasehistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='servicepurchasehistory',
            index=models.Index(fields=['-created_at'], name='servicePurc_created_1872c6_idx'),
        ),
    ]
