# Generated by Django 5.2.8 on 2025-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePurchaseHistory', '0004_alter_servicepurchasehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepurchasehistory',
            name='city',
            field=models.CharField(choices=[('حمص', 'العادية حمص'), ('إدلب', 'إدلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('دير الزور', 'دير الزور'), ('ريف دمشق', 'ريف دمشق'), ('درعا', 'درعا'), ('طرطوس', 'طرطوس'), ('اللاذقية', 'اللاذقية'), ('الحسكة', 'الحسكة'), ('قنيطرة', 'قنيطرة'), ('حماة', 'حماة'), ('الرقة', 'الرقة')], default='حمص', max_length=30),
        ),
    ]
