# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(default='', max_length=70)),
                ('source_id', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('content', models.TextField(default='', max_length=1000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('read', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
