# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_name', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('exam', 'Exam'), ('note', 'Note')], default='', max_length=50)),
                ('content_public_id', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
