# Generated by Django 5.2.8 on 2025-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_image'),
        ('lessons', '0002_alter_lessons_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='lessons',
            index=models.Index(fields=['-created_at'], name='lessons_les_created_4bb524_idx'),
        ),
    ]
