# Generated by Django 5.2.8 on 2025-12-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lessons_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='lesson_name',
        ),
    ]
