# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=35, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_for', models.CharField(choices=[('exam', 'امتحان'), ('note', 'نوطة'), ('course', 'دورة'), ('offer', 'عرض')], default='امتحان', max_length=50)),
                ('discount_type', models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_code', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('number_of_uses', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_remaining_uses', models.IntegerField(blank=True, default=1000000, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
