# Generated by Django 5.2.5 on 2025-11-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discountCodes', '0002_initial'),
        ('notes', '0001_initial'),
        ('publisherOffers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcodes',
            name='note_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
        migrations.AddField(
            model_name='discountcodes',
            name='offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisherOffers.publisheroffers'),
        ),
    ]
